INSERT INTO
	Anime (Anime_name, Total_Episode, Dub, Genre, IMBD_rating)
VALUES
('Naruto',220,'Hindi','Action',8.4),
('Naruto Shippuden',500,'Hindi','Action',8.7),
('One Piece',1070,'Japness','Adventure',9.0),
('Attack on Titan',87,'English','Action',9.1),
('Death Note',37,'All','Mystery',9.0),
('Demon Slayer',55,'Hindi','Action',8.8),
('Jujutsu Kaisen',48,'English','Action',8.7),
('Tokyo Ghoul',48,'Japness','Mystery',7.8),
('Fullmetal Alchemist',64,'All','Adventure',9.1),
('Dragon Ball Z',291,'Hindi','Action',8.5),

('Bleach',366,'English','Action',8.2),
('My Hero Academia',138,'Hindi','Action',8.3),
('Black Clover',170,'Japness','Fantasy',8.2),
('Fairy Tail',328,'Hindi','Adventure',7.9),
('Hunter x Hunter',148,'English','Adventure',9.0),
('Sword Art Online',96,'All','Fantasy',7.6),
('Re Zero',50,'Japness','Fantasy',8.3),
('Steins Gate',24,'English','Mystery',9.0),
('Mob Psycho 100',37,'All','Comedy',8.6),
('One Punch Man',24,'Hindi','Comedy',8.7),

('Tokyo Revengers',50,'English','Action',7.9),
('Chainsaw Man',12,'Japness','Action',8.6),
('Blue Lock',24,'Hindi','Action',8.4),
('Haikyuu',85,'English','Comedy',8.8),
('Kuroko Basketball',75,'All','Comedy',8.2),
('Dr Stone',35,'Japness','Adventure',8.3),
('Vinland Saga',48,'English','Action',8.9),
('Berserk',25,'Japness','Fantasy',8.5),
('Akame ga Kill',24,'Hindi','Action',7.8),
('Code Geass',50,'All','Mystery',8.7),

('Future Diary',26,'English','Mystery',7.6),
('Parasyte',24,'Japness','Mystery',8.3),
('Noragami',25,'Hindi','Adventure',8.0),
('Angel Beats',13,'English','Fantasy',7.9),
('Clannad',44,'All','Romance',8.4),
('Your Lie in April',22,'Japness','Romance',8.6),
('Toradora',25,'English','Romance',8.3),
('Golden Time',24,'Hindi','Romance',7.7),
('Kaguya Sama',37,'All','Comedy',8.7),
('Spy x Family',37,'Hindi','Comedy',8.5),

('Overlord',52,'Japness','Fantasy',7.9),
('That Time I Got Reincarnated',48,'English','Fantasy',8.1),
('No Game No Life',12,'All','Fantasy',8.2),
('Log Horizon',62,'Japness','Adventure',7.8),
('Goblin Slayer',24,'English','Fantasy',7.5),
('Made in Abyss',25,'All','Adventure',8.6),
('Erased',12,'Hindi','Mystery',8.5),
('Monster',74,'English','Mystery',8.9),
('Psycho Pass',41,'Japness','Mystery',8.3),
('Great Pretender',23,'All','Comedy',8.1),

('Gintama',367,'Japness','Comedy',8.8),
('Trigun',26,'English','Action',8.2),
('Samurai Champloo',26,'All','Adventure',8.5),
('Cowboy Bebop',26,'English','Adventure',8.9),
('FLCL',6,'Japness','Comedy',8.1),
('Hellsing Ultimate',10,'All','Action',8.3),
('Devilman Crybaby',10,'English','Fantasy',7.8),
('Dororo',24,'Japness','Action',8.4),
('Inuyasha',167,'Hindi','Adventure',7.9),
('Yashahime',48,'English','Adventure',7.2),

('Black Lagoon',29,'All','Action',8.0),
('D Gray Man',103,'Japness','Action',7.9),
('Blue Exorcist',37,'English','Fantasy',7.6),
('Seraph of the End',24,'All','Fantasy',7.5),
('Fire Force',48,'Hindi','Action',7.7),
('Soul Eater',51,'English','Fantasy',7.8),
('Zom 100',12,'Japness','Comedy',7.9),
('Mashle',12,'All','Comedy',7.6),
('The Eminence in Shadow',32,'English','Fantasy',8.1),
('Ranking of Kings',23,'Japness','Adventure',8.5),

('91 Days',12,'English','Mystery',7.8),
('Bungo Stray Dogs',61,'All','Mystery',8.2),
('Classroom of the Elite',38,'Japness','Mystery',7.9),
('Tomodachi Game',12,'English','Mystery',7.6),
('Another',12,'All','Mystery',7.5),
('Durarara',60,'Japness','Mystery',8.1),
('K Project',25,'English','Action',7.4),
('Aldnoah Zero',24,'All','Action',7.3),
('God of Highschool',13,'English','Action',7.2),
('Tower of God',13,'Japness','Adventure',7.8),

('Record of Ragnarok',27,'All','Action',7.4),
('Plunderer',24,'Hindi','Action',6.8),
('Darling in the Franxx',24,'English','Romance',7.4),
('Horimiya',26,'All','Romance',8.1),
('My Dress Up Darling',12,'Japness','Romance',8.0),
('Rent a Girlfriend',36,'English','Romance',7.0),
('Komi Cant Communicate',24,'All','Comedy',7.9),
('Uzaki Chan Wants to Hangout',25,'Hindi','Comedy',7.2),
('The Devil is a Part Timer',37,'English','Comedy',7.8),
('Love Chunibyo',24,'Japness','Romance',7.7),

('Orange',13,'All','Romance',7.6),
('Plastic Memories',13,'English','Romance',7.8),
('Anohana',11,'Japness','Romance',8.3),
('Charlotte',13,'All','Fantasy',7.9),
('The Melancholy of Haruhi',28,'English','Comedy',7.7),
('Lucky Star',24,'Japness','Comedy',7.5),
('Daily Life of Highschool Boys',12,'All','Comedy',7.8),
('Nichijou',26,'Japness','Comedy',8.4),
('Sk8 the Infinity',12,'English','Adventure',8.0),
('Free Swimming',37,'All','Adventure',7.6);