           -- Advanced (Project Level Queries) --

-- (1)Rank anime based on total revenue.

SELECT 
	a.anime_name, 
	SUM(m.Total_sales) AS Revenue,
	RANK() OVER(ORDER BY SUM(m.Total_sales) DESC) AS Rank_Position
FROM Anime a
JOIN anime_manga m
ON a.Anime_id = m.Anime_id
GROUP BY a.Anime_name;

-- (2)Find year-wise total manga sales.

SELECT
	Year(publish_date) as Year,
    SUM(Total_sales) as Total_Sales
FROM anime_manga
GROUP BY Year(publish_date)
ORDER BY Year;

-- (3)Find all manga where the available stock is less than 50,000 copies.

SELECT
	a.Anime_name,
	(m.publish_copies - m.sale_copies) AS Available_stock
FROM Anime a
JOIN Anime_manga m 
ON a.Anime_id = m.Anime_id
WHERE (m.publish_copies - m.sale_copies) < 50000
ORDER BY Available_stock;

-- (4)Calculate the available stock for each manga.

SELECT
	m.manga_id,
	a.anime_name,
	m.publish_copies,
    m.sale_copies,
	(m.publish_copies - m.sale_copies) AS Available_stock
FROM anime a
JOIN anime_manga m
ON a.anime_id = m.anime_id;

-- (5)Find anime that have no manga records.

SELECT 
	a.anime_name, 
	m.manga_id 
FROM anime a
LEFT JOIN anime_manga m 
ON a.anime_id = m.Anime_id
WHERE Manga_id IS NULL;

-- (6)Find anime whose revenue is above average revenue.

SELECT 
	a.anime_name,
    m.Total_sales 
FROM anime a
JOIN anime_manga m 
ON a.anime_id = m.anime_id
WHERE m.Total_sales > 
	(SELECT avg(m.Total_sales) FROM anime_manga m);

-- (7)Find total revenue generated by each anime.

SELECT
	a.Anime_name, 
	SUM(m.Total_sales) AS Revenue 
FROM Anime a
JOIN Anime_manga m 
ON a.Anime_id = m.Anime_id
GROUP BY a.Anime_name;

-- (8)Find top 5 revenue generating anime.

SELECT 
	a.anime_name,
	SUM(m.Total_sales) AS Revenue 
FROM Anime a
JOIN Anime_manga m 
ON a.anime_id = m.anime_id
GROUP BY a.Anime_name
ORDER BY Revenue DESC
LIMIT 5;

-- (9)Show genre-wise total revenue.

SELECT
	a.genre, 
    SUM(m.Total_sales) 
FROM anime a
JOIN anime_manga m 
ON a.Anime_id = m.Anime_id
GROUP BY a.Genre;

-- (10)Find anime where manga rating > 9.

SELECT
	a.anime_name,
	m.manga_rating 
FROM anime a
JOIN anime_manga m 
ON a.Anime_id = m.Anime_id
WHERE m.manga_rating > 9;